# Generated by Django 3.2.25 on 2025-04-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(choices=[('A', 'Admin'), ('C', 'Courrier'), ('P', 'Public')], default='P', max_length=1)),
                ('fecha_mod', models.DateField()),
                ('estado', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1)),
            ],
        ),
    ]
