# Generated by Django 3.2.25 on 2025-05-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('contraseña', models.CharField(default='', max_length=128)),
                ('correo', models.EmailField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('fecha_reg', models.DateField()),
                ('fecha_mod', models.DateField()),
                ('estado_usuario', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1)),
                ('nivel_acceso', models.CharField(choices=[('T', 'Total')], default='T', max_length=1)),
                ('ultimo_acceso', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('contraseña', models.CharField(default='', max_length=128)),
                ('correo', models.EmailField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('fecha_reg', models.DateField()),
                ('fecha_mod', models.DateField()),
                ('estado_usuario', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_entrega',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('peso', models.FloatField()),
                ('dir_entrega', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(default='', max_length=50)),
                ('contraseña', models.CharField(default='', max_length=128)),
                ('correo', models.EmailField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('fecha_reg', models.DateField()),
                ('fecha_mod', models.DateField()),
                ('estado_usuario', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.FloatField()),
                ('duracion_estimada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete_Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estado_entrega')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='app.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='ruta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ruta'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente'),
        ),
    ]
