# Generated by Django 3.2.25 on 2025-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_mod',
            field=models.DateField(auto_now=True),
        ),
    ]
