# Generated by Django 3.2.25 on 2025-04-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_fecha_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_entrega',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.FloatField()),
                ('duracion_estimada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('peso', models.FloatField()),
                ('fecha_aprox', models.DateField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estado_entrega')),
                ('ruta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
    ]
