# Generated by Django 3.2.25 on 2025-04-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estado_entrega_paquete_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='estado',
        ),
        migrations.CreateModel(
            name='Paquete_Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estado_entrega')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='app.paquete')),
            ],
        ),
    ]
